# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e802f0c31a2e200676874dab2e5735af230dff04a9585a0f2932a9c8233f8cae4b3ab841d16c00be0b56f5a0be16d91ebf667964c83d2e008287fa42840eec

test:
  secret_key_base: 094975c41ab17723bfd4d6a45caf4c7bc891a3343512f13a86883f3dc044cec5e18d13add1f02157f0fa628e7494334fb469d0f50641ddf607709ca4e20501de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 094975c41ab17723bfd4d6a45caf4c7bc891a3343512f13a86883f3dc044cec5e18d13add1f02157f0fa628e7494334fb469d0f50641ddf607709ca4e20501de
